version: 2

sources:
  - name: model
    description: Transformation of the city traffic taken by drones
    database: data_ware_house
    schema: public
    tables:
      - name: traffic_information
        columns:
          - name: track_id
            description: id of the track the vehicle is on
          - name: type
            description: type of the vehicle
          - name: traveled_d
            description: distance traveled by the vehicle
          - name: avg_speed
            description: distance traveled by the vehicle

      - name: trajectory_information
        columns:
          - name: id 
            description: unique identifier for the vehicle
            tests:
              - not_null
              - unique
          - name: track_id
            description: id of the track the vehicle is on
            tests:
              - not_null
          - name: lat
            description: latitude of the vehicle
          - name: lon
            description: longitude of the vehicle
          - name: speed
            description: speed of the vehicle at the given time
          - name: loan_acc
            description: loan account of the vehicle
          - name: lat_acc
            description: latitude of the vehicle at the given time
          - name: time
            description: time of the record 