traffic_data:
  outputs:
    dev:
      dbname: data_ware_house
      host: db
      pass: postgres
      port: 5432
      schema: public
      threads: 1
      type: postgres
      user: postgres
  target: dev
