dbt-postgres:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres
      user: postgres
      password: new_password
      port: 5432
      dbname: warehouse
      schema: public
      threads: 3
      keepalives_idle: 0 # default 0, indicating the system default