
version: 2

models:
  - name: all_vehicles
    description: |
      This dbt view returns all columns and rows from the "vehicle_data" table.

    columns:
      - name: track_id
        description: The unique identifier for each vehicle's track.

      - name: type
        description: The type of the vehicle.

      - name: traveled_d
        description: The distance traveled by the vehicle.

      - name: avg_speed
        description: The average speed of the vehicle.
  - name: avg_dist_by_type
    description: |
      This dbt table calculates the average traveled distance by vehicle type in the "vehicle_data" table.

    columns:
      - name: Vehicle Type
        description: The type of vehicle.

      - name: Average Distance
        description: Average traveled distance for each vehicle type.
  - name: avg_dist_by_type
    description: |
      This dbt view calculates the count of rows for each vehicle type in the "vehicle_data" table.

    columns:
      - name: Vehicle Type
        description: The type of vehicle.

      - name: Type Count
        description: Average traveled distance for each vehicle type.
  - name: total_dist_by_type
    description: |
      This dbt view calculates the total distance travled by each vechicle type.

    columns:
      - name: Total traveled Distance
        description: The total distance traveled by vehicles.

      - name: Vehicle type
        description: the type of Vechicle.
  - name: max_dis_and_speed_travel
    description: |
      This dbt table calculates the max distance and speed traveld by each vechicle type

    columns:
      - name: vehicle type
        description: the type of Vechicle
      
      - name: Max Traveled Distance
        description: the maximum value of the traveled distance for each vechicle type
      
      - name: Max Average Speed
        description: The maximum value of the average speed  for each vechicle type